# Generated by Django 5.1.4 on 2026-01-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='travel_fee',
            new_name='miscellaneous_fee',
        ),
    ]
