# Generated by Django 5.1.4 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panditprofile',
            name='photo',
            field=models.ImageField(default='', upload_to='pandits/'),
        ),
    ]
